nguage: ruby
env: RACK_ENV=development
sudo: false
rvm:
- 2.0.0
services:
- docker
before_install:
- docker pull mumuki/mumuki-wollok-worker
after_success:
- wget https://raw.githubusercontent.com/mumuki/mumuki-escualo/master/travis_deploy &&
  chmod u+x travis_deploy &&
  ./travis_deploy wollok runners2.mumuki.io

